# Generated by Django 3.1.2 on 2020-11-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('CH', 'Coach'), ('PR', 'Player')], default='PR', max_length=2),
        ),
    ]
