# Generated by Django 3.1.2 on 2020-12-14 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('createdBy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('yourTeam', models.CharField(choices=[('AW', 'Away'), ('HO', 'Home')], default='AW', max_length=2)),
                ('homeGoals', models.IntegerField(default=0)),
                ('homePoints', models.IntegerField(default=0)),
                ('awayGoals', models.IntegerField(default=0)),
                ('awayPoints', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isDummy', models.BooleanField(default=True)),
                ('position', models.CharField(choices=[('FWD', 'Forward'), ('DEF', 'Defense'), ('CNT', 'Center'), ('GOL', 'Goalie')], default='FWD', max_length=3)),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('fow', models.IntegerField(blank=True, null=True)),
                ('fol', models.IntegerField(blank=True, null=True)),
                ('ppg', models.IntegerField(blank=True, null=True)),
                ('shg', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('foPercent', models.FloatField(blank=True, null=True)),
                ('shootingPercent', models.FloatField(blank=True, null=True)),
                ('toi', models.IntegerField(blank=True, null=True)),
                ('sog', models.IntegerField(blank=True, null=True)),
                ('pim', models.IntegerField(blank=True, null=True)),
                ('dummy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.dummy')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('leave_date', models.DateTimeField(blank=True, null=True)),
                ('isDummy', models.BooleanField(default=True)),
                ('dummy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dummy')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='awayTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_team', to='main.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='createdBy',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='homeTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_team', to='main.team'),
        ),
    ]
