# Generated by Django 3.1.2 on 2020-12-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='toi',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
