# Generated by Django 3.1.2 on 2020-12-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201214_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='toi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
