# Generated by Django 3.1.2 on 2020-12-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201214_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='toi',
        ),
    ]
