# Generated by Django 3.1.2 on 2020-12-15 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_stats_toi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='dummy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dummy'),
        ),
    ]
