# Generated by Django 3.1.2 on 2020-12-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201215_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='shots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
